#!/usr/bin/env bash

if [ ! -f ./00-checkout-hashdist ]; then
    echo "Must be run from within the bootstrap-files directory"
    exit 1
fi

HIT="$(pwd)/hashdist/bin/hit"

rm -f default
cd hashstack

case "$(uname -s)" in
    Darwin)
	echo 'This is Mac OS X'
	cp ../hashconf/default-darwin.yaml default.yaml
	"$HIT" develop -f default.yaml "$LOCAL"
	;;
    Linux)
	echo 'This is Linux'
	cp ../hashconf/default-linux.yaml default.yaml
	"$HIT" develop -f -j 8 default.yaml "$LOCAL"
	;;
    CYGWIN*|MINGW32*|MSYS*)
	echo 'MS Windows is not supported'
	exit 1
	;;
    *)
	echo 'other OS (or missing cases for above OSs) is not supported'
	exit 1
	;;
esac

